import { Skeleton } from "@mui/material";
import css from "./homeSkeleton.module.css";
export const HomeSkeleton = () => (
  <div className="container">
    <div className={css.banners}>
      <Skeleton
        className={css.skeleton}
        variant="rectangular"
        width="50%"
        height={400}
      />
      <Skeleton
        className={css.skeleton}
        variant="rectangular"
        width="50%"
        height={400}
      />
    </div>
    <div className={css.header}>
      <Skeleton
        className={css.skeleton}
        variant="text"
        width={150}
        height={50}
      />
      <Skeleton
        className={css.skeleton}
        variant="text"
        width={150}
        height={50}
      />
    </div>
    <ul className={css.list}>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
      <li>
        <Skeleton
          className={css.skeleton}
          variant="rectangular"
          width={304}
          height={388}
        />
        <div className={css.up}>
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={120}
            height={50}
          />
          <Skeleton
            className={css.skeletonSpecial}
            variant="text"
            width={100}
            height={50}
          />
        </div>
        <ul className={css.ul}>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
          <li>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={72}
              height={50}
            />
          </li>
        </ul>
        <div className={css.down}>
          <div>
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
            <Skeleton
              className={css.skeletonSpecial}
              variant="text"
              width={100}
              height={50}
            />
          </div>
          <Skeleton
            className={css.skeletonSpecial}
            variant="rectangular"
            width={120}
            height={70}
          />
        </div>
      </li>
    </ul>
  </div>
);
